global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_monitoring"
    static_configs:
      - targets: ["host.docker.internal:5000"]  # Update with your API or exporter

  - job_name: "system_metrics"
    static_configs:
      - targets: ["host.docker.internal:9100"]  # For node exporter
